### ISSUE TITLE
error, fails to start

### ISSUE THREAD

**Issue by ghost** [busheezy/server-redirect-node-steam-bot#1]
root@game:/home/steam/steamcmd/csgo/server-redirect-node-steam-bot# npm start

> server-redirect-node-steam-bot@1.1.5 start /home/steam/steamcmd/csgo/server-redirect-node-steam-bot
> node app.js

Server running on port 19855

/home/steam/steamcmd/csgo/server-redirect-node-steam-bot/node_modules/steam/node_modules/steam-crypto/index.js:6
  var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);
                                 ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at Object.exports.generateSessionKey (/home/steam/steamcmd/csgo/server-redirect-node-steam-bot/node_modules/steam/node_modules/steam-crypto/index.js:6:34)
    at SteamClient.handlers.(anonymous function) (/home/steam/steamcmd/csgo/server-redirect-node-steam-bot/node_modules/steam/lib/steam_client.js:216:44)
    at SteamClient._netMsgReceived (/home/steam/steamcmd/csgo/server-redirect-node-steam-bot/node_modules/steam/lib/steam_client.js:157:26)
    at Connection.EventEmitter.emit (events.js:95:17)
    at Connection._readPacket (/home/steam/steamcmd/csgo/server-redirect-node-steam-bot/node_modules/steam/lib/connection.js:50:8)
    at Connection.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Connection.Readable.push (_stream_readable.js:127:10)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by busheezy** [comment]
Closing. Let me know if you still have issues.
