### ISSUE TITLE
something problem after cs go update

### ISSUE THREAD

**Issue by csgentr** [busheezy/server-redirect-node-steam-bot#2]
when I press to connect button from server, the bot giving me this error. before update it was working very well..

`/home/server-redirect-node-steam-bot/node_modules/steamidconvert/index.js:80
      throw err
      ^

Error: Invalid SteamID
    at SteamConvert.convertTo64 (/home/server-redirect-node-steam-bot/node_modules/steamidconvert/index.js:70:13)
    at Carrier.<anonymous> (/home/server-redirect-node-steam-bot/app.js:147:26)
    at emitOne (events.js:77:13)
    at Carrier.emit (events.js:169:7)
    at /home/server-redirect-node-steam-bot/node_modules/carrier/lib/carrier.js:24:12
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
`

**Comment by busheezy** [comment]
Closing. Let me know if you still have issues.
